const LEVELS = [
  {title:'Gerbang Sekolah',book:'Buku Profil',hint:'Temukan Buku Profil di dekat gerbang.',questions:[{type:'essay',text:'Apa yang anda ketahui dari sekolah SMK 17 Muncar?',key:'pengetahuan_sekolah'}]},
  {title:'Perpustakaan Program Keahlian',book:'Buku Program Keahlian',hint:'Cari Buku Program Keahlian lalu jawab 6 pertanyaan.',questions:[
    {type:'mc',text:'AKL adalah Akuntansi Keuangan Lembaga. Bidang ini terutama mempelajari tentang...',options:['Pengelolaan transaksi, pencatatan dan pelaporan keuangan','Tata boga dan pelayanan restoran','Perbaikan mesin kendaraan','Pemrograman aplikasi mobile'],answer:0,key:'akl'},
    {type:'mc',text:'BDP adalah Bisnis Daring dan Pemasaran. Bidang ini terutama mempelajari tentang...',options:['Strategi bisnis, pemasaran, penjualan dan perdagangan secara daring maupun luring','Pengelasan logam dan fabrikasi','Administrasi jaringan komputer','Perawatan mesin kendaraan'],answer:0,key:'bdp'},
    {type:'mc',text:'PH adalah Perhotelan. Bidang ini terutama mempelajari tentang...',options:['Pelayanan akomodasi, tata graha, front office, makanan-minuman dan layanan tamu','Akuntansi lembaga keuangan','Pemrograman website','Teknik pengelasan'],answer:0,key:'ph'},
    {type:'mc',text:'RPL adalah Rekayasa Perangkat Lunak. Bidang ini terutama mempelajari tentang...',options:['Pengembangan perangkat lunak, pemrograman, basis data, web dan aplikasi digital','Pelayanan kamar hotel','Pemasaran produk secara langsung saja','Perbaikan sistem rem kendaraan'],answer:0,key:'rpl'},
    {type:'mc',text:'TO adalah Teknik Otomotif. Bidang ini terutama mempelajari tentang...',options:['Perawatan, perbaikan dan teknologi kendaraan bermotor','Pengelolaan transaksi akuntansi','Pembuatan aplikasi web','Pelayanan front office hotel'],answer:0,key:'to'},
    {type:'mc',text:'TP adalah Teknik Pengelasan. Bidang ini terutama mempelajari tentang...',options:['Teknik penyambungan logam menggunakan proses pengelasan dan pekerjaan fabrikasi','Strategi promosi di media sosial','Administrasi hotel','Pemrograman Python'],answer:0,key:'tp'}
  ]},
  {title:'Taman Minat',book:'Buku Minat',hint:'Temukan Buku Minat lalu ceritakan jurusan pilihanmu.',questions:[{type:'essay',text:'Jika kamu sekolah di SMK 17 Muncar, kamu berminat memilih jurusan apa? Jelaskan pilihanmu.',key:'minat_jurusan'}]},
  {title:'Ruang Motivasi',book:'Buku Motivasi',hint:'Cari Buku Motivasi dan tuliskan alasan pilihanmu.',questions:[{type:'essay',text:'Kenapa kamu minat di jurusan tersebut?',key:'alasan_minat'}]},
  {title:'Laboratorium Impian',book:'Buku Impian',hint:'Temukan Buku Impian. Tulis hal yang ingin kamu capai.',questions:[{type:'essay',text:'Apa yang ingin kamu capai setelah belajar di SMK 17 Muncar?',key:'keinginan'}]},
  {title:'Menara Cita-Cita',book:'Buku Cita-Cita',hint:'Naik ke area menara dan temukan Buku Cita-Cita.',questions:[{type:'essay',text:'Apa cita-citamu? Jelaskan secara singkat.',key:'cita_cita'}]},
  {title:'Pos Kontak',book:'Buku Kontak',hint:'Temukan Buku Kontak dan tuliskan nomor WhatsApp aktifmu.',questions:[{type:'essay',text:'Nomor WhatsApp aktif kamu (contoh: 081234567890)',key:'whatsapp',inputType:'tel'}]},
  {title:'Peta Alamat',book:'Buku Data Peserta',hint:'Temukan Buku Data Peserta dan tuliskan alamat tempat tinggalmu.',questions:[{type:'essay',text:'Alamat tempat tinggal kamu.',key:'alamat'}]}
];
const TOTAL_LEVELS=LEVELS.length;
const state={user:null,currentLevel:0,unlocked:1,score:0,books:[],answers:{},qIndex:0,bookFound:false,raf:null,keys:{}};
const $=id=>document.getElementById(id);
const clamp=(v,min,max)=>Math.max(min,Math.min(max,v));
const progressKey=u=>`smkPintarProgress_${String(u).toLowerCase()}`;
const userKey='smkPintarCurrentUser';
function escapeHTML(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));}
function toast(msg){const t=$('toast');t.textContent=msg;t.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.classList.remove('show'),2200)}
function showScreen(id){['loginScreen','dashboardScreen','gameScreen'].forEach(x=>$(x).classList.add('hidden'));$(id).classList.remove('hidden');window.scrollTo({top:0,behavior:'instant'});}
function saveLocal(){if(!state.user)return;localStorage.setItem(progressKey(state.user.username),JSON.stringify({unlocked:state.unlocked,score:state.score,books:state.books,answers:state.answers,currentLevel:state.currentLevel}));localStorage.setItem(userKey,JSON.stringify(state.user));}
function loadLocal(username){try{const x=JSON.parse(localStorage.getItem(progressKey(username))||'null');state.unlocked=x?.unlocked||1;state.score=x?.score||0;state.books=Array.isArray(x?.books)?x.books:[];state.answers=x?.answers||{};state.currentLevel=Math.min(x?.currentLevel||0,TOTAL_LEVELS-1)}catch(e){state.unlocked=1;state.score=0;state.books=[];state.answers={};state.currentLevel=0}}
function resetState(){state.currentLevel=0;state.unlocked=1;state.score=0;state.books=[];state.answers={};state.qIndex=0;state.bookFound=false;}
async function hashText(value){if(window.crypto?.subtle){const buf=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(value));return [...new Uint8Array(buf)].map(b=>b.toString(16).padStart(2,'0')).join('')}return value}
function getDemoUsers(){try{return JSON.parse(localStorage.getItem('smkPintarUsers')||'[]')}catch(e){return []}}
function setDemoUsers(v){localStorage.setItem('smkPintarUsers',JSON.stringify(v))}
function getDemoScores(){try{return JSON.parse(localStorage.getItem('smkPintarScores')||'[]')}catch(e){return []}}
function setDemoScores(v){localStorage.setItem('smkPintarScores',JSON.stringify(v))}
async function demoApi(action,p={}){
  const users=getDemoUsers();
  if(action==='register'){
    const username=String(p.username||'').trim();
    if(users.some(u=>u.username.toLowerCase()===username.toLowerCase()))return {ok:false,error:'Username sudah digunakan.'};
    const passwordHash=await hashText(String(p.password||''));
    const user={username,passwordHash,nama:String(p.nama||''),kelas:String(p.kelas||'')};users.push(user);setDemoUsers(users);return {ok:true,user:{username,nama:user.nama,kelas:user.kelas}};
  }
  if(action==='login'){
    if(p.username==='demo'&&p.password==='smkpintar')return {ok:true,user:{username:'demo',nama:'Peserta Demo',kelas:'-'}};
    const h=await hashText(String(p.password||''));const u=users.find(x=>x.username.toLowerCase()===String(p.username||'').toLowerCase()&&(x.passwordHash===h||x.password===p.password));
    return u?{ok:true,user:{username:u.username,nama:u.nama,kelas:u.kelas}}:{ok:false,error:'Username/password salah.'};
  }
  if(action==='saveAnswer')return {ok:true};
  if(action==='saveProgress'){
    const rows=getDemoScores(),i=rows.findIndex(x=>x.username.toLowerCase()===String(p.username).toLowerCase());
    const item={username:p.username,nama:state.user?.nama||p.username,kelas:state.user?.kelas||'-',score:Number(p.score)||0,books:String(p.books||'').split(',').filter(Boolean).length,updatedAt:Date.now()};
    if(i>=0)rows[i]={...rows[i],...item,score:Math.max(rows[i].score,item.score),books:Math.max(rows[i].books,item.books)};else rows.push(item);setDemoScores(rows);return {ok:true};
  }
  if(action==='leaderboard'){return {ok:true,rows:getDemoScores().sort((a,b)=>b.score-a.score||b.books-a.books||String(a.nama).localeCompare(String(b.nama))).slice(0,50)}}
  return {ok:true};
}
async function api(action,payload={}){
  if(CONFIG.DEMO_MODE||!CONFIG.GOOGLE_SCRIPT_URL||CONFIG.GOOGLE_SCRIPT_URL.includes('PASTE_'))return demoApi(action,payload);
  try{const r=await fetch(CONFIG.GOOGLE_SCRIPT_URL,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({action,...payload})});return await r.json()}catch(e){console.warn(e);return {ok:false,error:'Server tidak terhubung. Progres lokal tetap tersimpan.'}}
}
async function login(username,password){const r=await api('login',{username,password});if(r.ok&&r.user){state.user=r.user;loadLocal(username);saveLocal();return true}return false}
async function register(){const nama=$('regNama').value.trim(),kelas=$('regKelas').value.trim(),username=$('regUsername').value.trim(),password=$('regPassword').value;if(nama.length<2||kelas.length<1){$('loginMsg').textContent='Nama dan kelas wajib diisi.';return}if(!/^[A-Za-z0-9._-]{3,30}$/.test(username)){$('loginMsg').textContent='Username: 3–30 karakter, hanya huruf/angka . _ -.';return}if(password.length<6){$('loginMsg').textContent='Password minimal 6 karakter.';return}$('loginMsg').textContent='Mendaftarkan peserta...';const r=await api('register',{username,password,nama,kelas});if(r.ok&&r.user){state.user=r.user;resetState();saveLocal();$('registerForm').reset();renderDashboard();showScreen('dashboardScreen');toast('Pendaftaran berhasil!')}else $('loginMsg').textContent=r.error||'Pendaftaran gagal.'}
function renderDashboard(){
  $('userBadge').textContent=`👤 ${state.user?.nama||state.user?.username||'-'}`;$('statLevel').textContent=`${state.unlocked}/${TOTAL_LEVELS}`;$('statBooks').textContent=`${state.books.length}/${TOTAL_LEVELS}`;$('statScore').textContent=state.score;$('profileBox').innerHTML=`<p><b>Username:</b> ${escapeHTML(state.user.username)}</p><p><b>Nama:</b> ${escapeHTML(state.user.nama||'-')}</p><p><b>Kelas:</b> ${escapeHTML(state.user.kelas||'-')}</p>`;
  const map=$('levelMap');map.innerHTML='';LEVELS.forEach((lv,i)=>{const open=i<state.unlocked;const d=document.createElement('button');d.type='button';d.className=`level-card ${open?'':'locked'} ${i===state.currentLevel?'active':''}`;d.disabled=!open;d.innerHTML=`<span class="num">${open?'📖':'🔒'} ${i+1}</span><span class="name">${escapeHTML(lv.title)}</span>`;d.onclick=()=>startLevel(i);map.appendChild(d)});
  $('continueBtn').textContent=state.unlocked>=TOTAL_LEVELS?'🏆 Lihat Level Terakhir':'▶ Lanjutkan Petualangan';renderLeaderboard();
}
async function renderLeaderboard(){const box=$('leaderboard');box.innerHTML='<div class="leaderboard-empty">Memuat papan skor...</div>';const r=await api('leaderboard');const rows=r.rows||[];if(!rows.length){box.innerHTML='<div class="leaderboard-empty">Belum ada skor tersimpan. Jadilah pemain pertama! 🎮</div>';return}box.innerHTML=rows.map((x,i)=>`<div class="leaderboard-row"><div class="rank">#${i+1}</div><div><div class="player-name">${escapeHTML(x.nama||x.username)}</div><div class="player-class">${escapeHTML(x.kelas||'-')} · @${escapeHTML(x.username)}</div></div><div class="score">⭐ ${Number(x.score)||0}</div><div class="player-class books-score">${Number(x.books)||0}/${TOTAL_LEVELS} buku</div></div>`).join('')}
function updateStats(){const n=LEVELS[state.currentLevel];$('sideScore').textContent=state.score;$('sideBooks').textContent=`${state.books.length}/${TOTAL_LEVELS}`;$('sideLevel').textContent=`${state.currentLevel+1}/${TOTAL_LEVELS}`;$('gameLevel').textContent=`LEVEL ${state.currentLevel+1}/${TOTAL_LEVELS}`;$('levelLabel').textContent=`LEVEL ${state.currentLevel+1}`;$('levelTitle').textContent=n.title;$('progressBar').style.width=`${(state.qIndex/n.questions.length)*100}%`;const bc=$('bookCollection');bc.innerHTML='';for(let i=0;i<TOTAL_LEVELS;i++){const d=document.createElement('div');d.className=`book-item ${state.books.includes(i)?'':'locked'}`;d.textContent=state.books.includes(i)?'📖':'🔒';d.title=LEVELS[i].book;bc.appendChild(d)}}
function startLevel(index){if(index<0||index>=TOTAL_LEVELS||index>=state.unlocked)return;cancelAnimationFrame(state.raf);state.currentLevel=index;state.qIndex=0;state.bookFound=false;state.keys={};$('questionPanel').classList.add('hidden');$('levelComplete').classList.add('hidden');$('hintText').textContent=LEVELS[index].hint;showScreen('gameScreen');updateStats();startCanvas()}
function startCanvas(){
  const canvas=$('gameCanvas'),ctx=canvas.getContext('2d'),W=canvas.width,H=canvas.height;const player={x:65,y:H-85,w:30,h:38,speed:4.2};const book={x:W-105,y:70,w:34,h:42};const keys=state.keys;const obstacles=[];for(let i=0;i<7;i++)obstacles.push({x:120+i*105+(i%2)*20,y:95+(i*47)%280,w:70,h:32});const trees=[];for(let i=0;i<14;i++)trees.push({x:30+(i*83)%840,y:40+(i*97)%400});
  const collide=(a,b)=>a.x<b.x+b.w&&a.x+a.w>b.x&&a.y<b.y+b.h&&a.y+a.h>b.y;
  const move=()=>{let nx=player.x,ny=player.y;if(keys.ArrowLeft||keys.a)nx-=player.speed;if(keys.ArrowRight||keys.d)nx+=player.speed;if(keys.ArrowUp||keys.w)ny-=player.speed;if(keys.ArrowDown||keys.s)ny+=player.speed;let test={x:nx,y:player.y,w:player.w,h:player.h};if(nx>=0&&nx+player.w<=W&&!obstacles.some(o=>collide(test,o)))player.x=nx;test={x:player.x,y:ny,w:player.w,h:player.h};if(ny>=0&&ny+player.h<=H&&!obstacles.some(o=>collide(test,o)))player.y=ny};
  const draw=()=>{ctx.clearRect(0,0,W,H);ctx.fillStyle='#102b25';ctx.fillRect(0,0,W,H);ctx.strokeStyle='rgba(97,218,251,.05)';for(let x=0;x<W;x+=40){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,H);ctx.stroke()}for(let y=0;y<H;y+=40){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(W,y);ctx.stroke()}ctx.fillStyle='#5b4a35';ctx.fillRect(0,H-135,W,95);trees.forEach(t=>{ctx.fillStyle='#553b25';ctx.fillRect(t.x,t.y+15,9,25);ctx.fillStyle='#1d633f';ctx.beginPath();ctx.arc(t.x+4,t.y+12,18,0,Math.PI*2);ctx.fill()});obstacles.forEach(o=>{ctx.fillStyle='#34455c';ctx.fillRect(o.x,o.y,o.w,o.h);ctx.fillStyle='#65758b';ctx.fillRect(o.x+7,o.y+6,o.w-14,7)});if(!state.bookFound){const g=ctx.createRadialGradient(book.x+17,book.y+21,3,book.x+17,book.y+21,60);g.addColorStop(0,'rgba(255,215,70,.5)');g.addColorStop(1,'rgba(255,215,70,0)');ctx.fillStyle=g;ctx.fillRect(book.x-55,book.y-55,140,150);ctx.font='38px Arial';ctx.fillText('📖',book.x,book.y+37)}ctx.fillStyle='#61dafb';ctx.fillRect(player.x,player.y+13,player.w,player.h-13);ctx.fillStyle='#ffd3a5';ctx.beginPath();ctx.arc(player.x+15,player.y+9,11,0,Math.PI*2);ctx.fill();ctx.fillStyle='#17213a';ctx.fillRect(player.x+5,player.y,20,6);ctx.font='bold 12px Arial';ctx.fillStyle='#fff';ctx.fillText((state.user?.nama||'PEMAIN').slice(0,18),player.x-12,player.y-8);if(collide(player,book)&&!state.bookFound){ctx.fillStyle='#fff';ctx.font='bold 15px Arial';ctx.fillText('TEKAN 📖 UNTUK AMBIL',book.x-72,book.y-18)}move();state.raf=requestAnimationFrame(draw)};
  const action=()=>{if(!state.bookFound&&collide(player,book)){state.bookFound=true;showQuestion()}};
  state.gameAction=action;draw();
}
function showQuestion(){const q=LEVELS[state.currentLevel].questions[state.qIndex];$('questionPanel').classList.remove('hidden');$('levelComplete').classList.add('hidden');$('questionCounter').textContent=`PERTANYAAN ${state.qIndex+1}/${LEVELS[state.currentLevel].questions.length}`;$('questionType').textContent=q.type==='mc'?'PILIHAN GANDA':'ESAI';$('questionText').textContent=q.text;const area=$('answerArea');area.innerHTML='';if(q.type==='mc'){q.options.forEach((opt,i)=>{const l=document.createElement('label');l.className='choice';l.innerHTML=`<input type="radio" name="choice" value="${i}"><span>${escapeHTML(opt)}</span>`;area.appendChild(l)})}else{const ta=document.createElement('textarea');ta.id='essayAnswer';ta.className='answer-textarea';ta.inputMode=q.inputType==='tel'?'tel':'text';ta.placeholder='Tuliskan jawaban kamu di sini...';ta.value=state.answers[q.key]||'';area.appendChild(ta)}$('answerMsg').textContent='';updateStats();setTimeout(()=>$('questionPanel').scrollIntoView({behavior:'smooth',block:'center'}),40)}
async function submitAnswer(){const q=LEVELS[state.currentLevel].questions[state.qIndex];let value='',correct=true;if(q.type==='mc'){const selected=document.querySelector('input[name="choice"]:checked');if(!selected){$('answerMsg').textContent='Pilih salah satu jawaban terlebih dahulu.';return}value=Number(selected.value);correct=value===q.answer;if(correct)state.score+=10;else state.score=Math.max(0,state.score-2)}else{value=$('essayAnswer').value.trim();if(value.length<3){$('answerMsg').textContent='Jawaban masih terlalu singkat. Silakan isi lebih lengkap.';return}state.answers[q.key]=value;state.score+=5}const r=await api('saveAnswer',{username:state.user.username,level:state.currentLevel+1,question:q.text,answer:q.type==='mc'?q.options[value]:value,correct});if(r?.ok===false)toast('Server belum tersambung. Jawaban tetap dicatat di perangkat.');if(q.type==='mc'&&!correct){$('answerMsg').textContent='Jawaban belum tepat. Coba lagi.';return}state.qIndex++;saveLocal();if(state.qIndex<LEVELS[state.currentLevel].questions.length){showQuestion();return}completeLevel()}
async function completeLevel(){const idx=state.currentLevel;if(!state.books.includes(idx))state.books.push(idx);state.unlocked=Math.max(state.unlocked,Math.min(TOTAL_LEVELS,idx+2));saveLocal();await api('saveProgress',{username:state.user.username,level:idx+1,score:state.score,books:state.books.join(','),answers:JSON.stringify(state.answers)});$('questionPanel').classList.add('hidden');$('levelComplete').classList.remove('hidden');const last=idx===TOTAL_LEVELS-1;$('completeTitle').textContent=last?'🎉 SEMUA LEVEL SELESAI!':'📖 Buku Berhasil Ditemukan!';$('completeText').textContent=last?`Selamat ${state.user.nama||''}! Kamu telah menyelesaikan seluruh petualangan dengan skor ${state.score}.`:`Keren! ${LEVELS[idx].book} berhasil ditemukan. Level berikutnya sudah terbuka.`;$('nextLevelBtn').classList.toggle('hidden',last);$('finishBtn').classList.toggle('hidden',!last);updateStats();renderLeaderboard()}
function setupMobileControls(){document.querySelectorAll('.mobile-controls button').forEach(btn=>{const key=btn.dataset.key;const start=e=>{e.preventDefault();if(key==='Space'){state.gameAction?.();return}state.keys[key]=true};const end=e=>{e.preventDefault();if(key!=='Space')state.keys[key]=false};btn.addEventListener('pointerdown',start);btn.addEventListener('pointerup',end);btn.addEventListener('pointercancel',end);btn.addEventListener('pointerleave',end)})}
document.addEventListener('keydown',e=>{if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight',' ','w','a','s','d','W','A','S','D'].includes(e.key)){if(['INPUT','TEXTAREA'].includes(document.activeElement?.tagName))return;e.preventDefault();const k=e.code==='Space'?'Space':e.key;state.keys[k]=true;if(k==='Space')state.gameAction?.()}});document.addEventListener('keyup',e=>{const k=e.code==='Space'?'Space':e.key;state.keys[k]=false});
$('loginTab').onclick=()=>{$('loginTab').classList.add('active');$('registerTab').classList.remove('active');$('loginForm').classList.remove('hidden');$('registerForm').classList.add('hidden');$('loginMsg').textContent=''};
$('registerTab').onclick=()=>{$('registerTab').classList.add('active');$('loginTab').classList.remove('active');$('registerForm').classList.remove('hidden');$('loginForm').classList.add('hidden');$('loginMsg').textContent=''};
$('registerForm').addEventListener('submit',e=>{e.preventDefault();register()});
$('loginForm').addEventListener('submit',async e=>{e.preventDefault();$('loginMsg').textContent='Memeriksa login...';const ok=await login($('username').value.trim(),$('password').value);if(ok){$('loginMsg').textContent='';renderDashboard();showScreen('dashboardScreen');toast('Login berhasil!')}else $('loginMsg').textContent='Username atau password salah.'});
$('refreshLeaderboard').onclick=renderLeaderboard;
$('logoutBtn').onclick=()=>{saveLocal();state.user=null;localStorage.removeItem(userKey);resetState();showScreen('loginScreen')};
$('backDashboard').onclick=()=>{cancelAnimationFrame(state.raf);saveLocal();renderDashboard();showScreen('dashboardScreen')};
$('continueBtn').onclick=()=>startLevel(Math.min(state.unlocked-1,TOTAL_LEVELS-1));
$('nextLevelBtn').onclick=()=>startLevel(state.currentLevel+1);
$('finishBtn').onclick=()=>{renderDashboard();showScreen('dashboardScreen')};
$('submitAnswer').onclick=submitAnswer;
$('resetBtn').onclick=()=>{if(confirm('Mulai ulang seluruh progres peserta ini?')){localStorage.removeItem(progressKey(state.user.username));resetState();saveLocal();renderDashboard();toast('Progres direset.')}};
window.addEventListener('beforeunload',saveLocal);setupMobileControls();
(async()=>{try{const u=JSON.parse(localStorage.getItem(userKey)||'null');if(u?.username){state.user=u;loadLocal(u.username);renderDashboard();showScreen('dashboardScreen');return}}catch(e){}showScreen('loginScreen')})();
